### PR TITLE
Allow to create translations keys directly from interface 

### PR DESCRIPTION
**Pull request by nchaulet**

### CODE REVIEW

**Comment by MattKetmo** [comment]
Thanks for this feature, very helpful.

However I'm not convinced by the actual ui/ux: 
- the md-fab mini button looks a bit weird, too much flashy and not well aligned with the title 
- The *Cancel* button seems do to nothing (?)
- Only accessible at the top of the page/group

What I would do for this:
- an classic fab button at the bottom right
- which open a $mdModal with a form
- that form contains 3 fields: a select or autocomplete to choose the resource, an input text for the key and a textarea to fill the default translation (eg. English)

I will try to make this from your branch to see what it could look like.

**Comment by MattKetmo** [comment]
wip in branch `feature/add-translation`

**Comment by nchaulet** [comment]
Thanks for your returns, my UI was a really quick and dirty solution.

**Comment by jdeniau** [comment]
Hi @MattKetmo 

Is it mergeable or not yet ?

**Comment by nchaulet** [comment]
I updated my PR to use the new modal

**Comment by nchaulet** [comment]
@MattKetmo Can you review this PR ? We really need this functionality

**Comment by MattKetmo** [comment]
Looks good. Sorry for the delay.
I've merged it on master and dump it as the `dev-master` version on cdn.openl10n.io (http://cdn.openl10n.io/app/releases/dev-master/app.js)

**Pull request closed without merging**
